/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/announcements-api';
export * from './apis/app-image-errors-api';
export * from './apis/assets-api';
export * from './apis/auth-api';
export * from './apis/batch-requests-api';
export * from './apis/cabinets-api';
export * from './apis/checkouts-api';
export * from './apis/content-types-api';
export * from './apis/credentials-api';
export * from './apis/document-file-actions-api';
export * from './apis/document-types-api';
export * from './apis/document-version-modification-backends-api';
export * from './apis/documents-api';
export * from './apis/downloads-api';
export * from './apis/event-type-namespaces-api';
export * from './apis/event-types-api';
export * from './apis/events-api';
export * from './apis/file-metadata-drivers-api';
export * from './apis/groups-api';
export * from './apis/index-instances-api';
export * from './apis/index-templates-api';
export * from './apis/keys-api';
export * from './apis/mailing-profiles-api';
export * from './apis/messages-api';
export * from './apis/metadata-types-api';
export * from './apis/notifications-api';
export * from './apis/objects-api';
export * from './apis/permissions-api';
export * from './apis/project-api';
export * from './apis/roles-api';
export * from './apis/saved-resultsets-api';
export * from './apis/search-api';
export * from './apis/search-models-api';
export * from './apis/smart-links-api';
export * from './apis/sources-api';
export * from './apis/tags-api';
export * from './apis/templates-api';
export * from './apis/trashed-documents-api';
export * from './apis/users-api';
export * from './apis/web-links-api';
export * from './apis/workflow-templates-api';

