/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ACLPermissionAdd
 */
export interface ACLPermissionAdd {
    /**
     * Primary key of the permission to add to the ACL.
     * @type {string}
     * @memberof ACLPermissionAdd
     */
    permission: string;
}

/**
 * Check if a given object implements the ACLPermissionAdd interface.
 */
export function instanceOfACLPermissionAdd(value: object): value is ACLPermissionAdd {
    if (!('permission' in value) || value['permission'] === undefined) return false;
    return true;
}

export function ACLPermissionAddFromJSON(json: any): ACLPermissionAdd {
    return ACLPermissionAddFromJSONTyped(json, false);
}

export function ACLPermissionAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): ACLPermissionAdd {
    if (json == null) {
        return json;
    }
    return {
        
        'permission': json['permission'],
    };
}

export function ACLPermissionAddToJSON(json: any): ACLPermissionAdd {
    return ACLPermissionAddToJSONTyped(json, false);
}

export function ACLPermissionAddToJSONTyped(value?: ACLPermissionAdd | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission': value['permission'],
    };
}

