/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AJAXTemplate
 */
export interface AJAXTemplate {
    /**
     * 
     * @type {string}
     * @memberof AJAXTemplate
     */
    readonly hexHash?: string;
    /**
     * 
     * @type {string}
     * @memberof AJAXTemplate
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof AJAXTemplate
     */
    readonly html?: string;
    /**
     * 
     * @type {string}
     * @memberof AJAXTemplate
     */
    readonly url?: string;
}

/**
 * Check if a given object implements the AJAXTemplate interface.
 */
export function instanceOfAJAXTemplate(value: object): value is AJAXTemplate {
    return true;
}

export function AJAXTemplateFromJSON(json: any): AJAXTemplate {
    return AJAXTemplateFromJSONTyped(json, false);
}

export function AJAXTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AJAXTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'hexHash': json['hex_hash'] == null ? undefined : json['hex_hash'],
        'name': json['name'] == null ? undefined : json['name'],
        'html': json['html'] == null ? undefined : json['html'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function AJAXTemplateToJSON(json: any): AJAXTemplate {
    return AJAXTemplateToJSONTyped(json, false);
}

export function AJAXTemplateToJSONTyped(value?: Omit<AJAXTemplate, 'hex_hash'|'name'|'html'|'url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

