/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoredCredential } from './StoredCredential';
import {
    StoredCredentialFromJSON,
    StoredCredentialFromJSONTyped,
    StoredCredentialToJSON,
    StoredCredentialToJSONTyped,
} from './StoredCredential';

/**
 * 
 * @export
 * @interface CredentialsList200Response
 */
export interface CredentialsList200Response {
    /**
     * 
     * @type {number}
     * @memberof CredentialsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof CredentialsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CredentialsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<StoredCredential>}
     * @memberof CredentialsList200Response
     */
    results: Array<StoredCredential>;
}

/**
 * Check if a given object implements the CredentialsList200Response interface.
 */
export function instanceOfCredentialsList200Response(value: object): value is CredentialsList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function CredentialsList200ResponseFromJSON(json: any): CredentialsList200Response {
    return CredentialsList200ResponseFromJSONTyped(json, false);
}

export function CredentialsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialsList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(StoredCredentialFromJSON)),
    };
}

export function CredentialsList200ResponseToJSON(json: any): CredentialsList200Response {
    return CredentialsList200ResponseToJSONTyped(json, false);
}

export function CredentialsList200ResponseToJSONTyped(value?: CredentialsList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(StoredCredentialToJSON)),
    };
}

