/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentVersionPage } from './DocumentVersionPage';
import {
    DocumentVersionPageFromJSON,
    DocumentVersionPageFromJSONTyped,
    DocumentVersionPageToJSON,
    DocumentVersionPageToJSONTyped,
} from './DocumentVersionPage';

/**
 * 
 * @export
 * @interface DocumentsVersionsPagesList200Response
 */
export interface DocumentsVersionsPagesList200Response {
    /**
     * 
     * @type {number}
     * @memberof DocumentsVersionsPagesList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentsVersionsPagesList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentsVersionsPagesList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<DocumentVersionPage>}
     * @memberof DocumentsVersionsPagesList200Response
     */
    results: Array<DocumentVersionPage>;
}

/**
 * Check if a given object implements the DocumentsVersionsPagesList200Response interface.
 */
export function instanceOfDocumentsVersionsPagesList200Response(value: object): value is DocumentsVersionsPagesList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function DocumentsVersionsPagesList200ResponseFromJSON(json: any): DocumentsVersionsPagesList200Response {
    return DocumentsVersionsPagesList200ResponseFromJSONTyped(json, false);
}

export function DocumentsVersionsPagesList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsVersionsPagesList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(DocumentVersionPageFromJSON)),
    };
}

export function DocumentsVersionsPagesList200ResponseToJSON(json: any): DocumentsVersionsPagesList200Response {
    return DocumentsVersionsPagesList200ResponseToJSONTyped(json, false);
}

export function DocumentsVersionsPagesList200ResponseToJSONTyped(value?: DocumentsVersionsPagesList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(DocumentVersionPageToJSON)),
    };
}

