"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDocumentVersionModificationBackendsList200Response = instanceOfDocumentVersionModificationBackendsList200Response;
exports.DocumentVersionModificationBackendsList200ResponseFromJSON = DocumentVersionModificationBackendsList200ResponseFromJSON;
exports.DocumentVersionModificationBackendsList200ResponseFromJSONTyped = DocumentVersionModificationBackendsList200ResponseFromJSONTyped;
exports.DocumentVersionModificationBackendsList200ResponseToJSON = DocumentVersionModificationBackendsList200ResponseToJSON;
exports.DocumentVersionModificationBackendsList200ResponseToJSONTyped = DocumentVersionModificationBackendsList200ResponseToJSONTyped;
const DocumentVersionModification_1 = require("./DocumentVersionModification");
/**
 * Check if a given object implements the DocumentVersionModificationBackendsList200Response interface.
 */
function instanceOfDocumentVersionModificationBackendsList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function DocumentVersionModificationBackendsList200ResponseFromJSON(json) {
    return DocumentVersionModificationBackendsList200ResponseFromJSONTyped(json, false);
}
function DocumentVersionModificationBackendsList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(DocumentVersionModification_1.DocumentVersionModificationFromJSON)),
    };
}
function DocumentVersionModificationBackendsList200ResponseToJSON(json) {
    return DocumentVersionModificationBackendsList200ResponseToJSONTyped(json, false);
}
function DocumentVersionModificationBackendsList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(DocumentVersionModification_1.DocumentVersionModificationToJSON)),
    };
}
