/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentType
 */
export interface DocumentType {
    /**
     * Amount of time after which documents of this type in the trash will be deleted.
     * @type {number}
     * @memberof DocumentType
     */
    'delete_time_period'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentType
     */
    'delete_time_unit'?: DocumentTypeDeleteTimeUnitEnum | null;
    /**
     * Time (in seconds) after which a document stub will be considered invalid and deleted, if pruning is enabled. This an optimization setting and should only be changed for specific circumstances.
     * @type {number}
     * @memberof DocumentType
     */
    'document_stub_expiration_interval'?: number;
    /**
     * Delete documents that do not contain any files after a configured expiration interval.
     * @type {boolean}
     * @memberof DocumentType
     */
    'document_stub_pruning_enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentType
     */
    'documents_url'?: string;
    /**
     * The class responsible for producing the actual filename used to store the uploaded documents.
     * @type {string}
     * @memberof DocumentType
     */
    'filename_generator_backend'?: string;
    /**
     * The arguments for the filename generator backend as a YAML dictionary.
     * @type {string}
     * @memberof DocumentType
     */
    'filename_generator_backend_arguments'?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentType
     */
    'id'?: number;
    /**
     * A short text identifying the document type.
     * @type {string}
     * @memberof DocumentType
     */
    'label': string;
    /**
     * 
     * @type {string}
     * @memberof DocumentType
     */
    'quick_label_list_url'?: string;
    /**
     * Amount of time after which documents of this type will be moved to the trash.
     * @type {number}
     * @memberof DocumentType
     */
    'trash_time_period'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentType
     */
    'trash_time_unit'?: DocumentTypeTrashTimeUnitEnum | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentType
     */
    'url'?: string;
}

export const DocumentTypeDeleteTimeUnitEnum = {
    Days: 'days',
    Hours: 'hours',
    Minutes: 'minutes'
} as const;

export type DocumentTypeDeleteTimeUnitEnum = typeof DocumentTypeDeleteTimeUnitEnum[keyof typeof DocumentTypeDeleteTimeUnitEnum];
export const DocumentTypeTrashTimeUnitEnum = {
    Days: 'days',
    Hours: 'hours',
    Minutes: 'minutes'
} as const;

export type DocumentTypeTrashTimeUnitEnum = typeof DocumentTypeTrashTimeUnitEnum[keyof typeof DocumentTypeTrashTimeUnitEnum];


