/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowTemplateTransition } from './workflow-template-transition';

/**
 * 
 * @export
 * @interface DocumentsWorkflowInstancesLogEntriesTransitionsList200Response
 */
export interface DocumentsWorkflowInstancesLogEntriesTransitionsList200Response {
    /**
     * 
     * @type {number}
     * @memberof DocumentsWorkflowInstancesLogEntriesTransitionsList200Response
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof DocumentsWorkflowInstancesLogEntriesTransitionsList200Response
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentsWorkflowInstancesLogEntriesTransitionsList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<WorkflowTemplateTransition>}
     * @memberof DocumentsWorkflowInstancesLogEntriesTransitionsList200Response
     */
    'results': Array<WorkflowTemplateTransition>;
}

