"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDocumentFilePage = instanceOfDocumentFilePage;
exports.DocumentFilePageFromJSON = DocumentFilePageFromJSON;
exports.DocumentFilePageFromJSONTyped = DocumentFilePageFromJSONTyped;
exports.DocumentFilePageToJSON = DocumentFilePageToJSON;
exports.DocumentFilePageToJSONTyped = DocumentFilePageToJSONTyped;
/**
 * Check if a given object implements the DocumentFilePage interface.
 */
function instanceOfDocumentFilePage(value) {
    return true;
}
function DocumentFilePageFromJSON(json) {
    return DocumentFilePageFromJSONTyped(json, false);
}
function DocumentFilePageFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'documentFileId': json['document_file_id'] == null ? undefined : json['document_file_id'],
        'documentFileUrl': json['document_file_url'] == null ? undefined : json['document_file_url'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'pageNumber': json['page_number'] == null ? undefined : json['page_number'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}
function DocumentFilePageToJSON(json) {
    return DocumentFilePageToJSONTyped(json, false);
}
function DocumentFilePageToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {};
}
