/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentTypeAdd
 */
export interface DocumentTypeAdd {
    /**
     * Primary key of the document type to add to the index template.
     * @type {string}
     * @memberof DocumentTypeAdd
     */
    documentType: string;
}

/**
 * Check if a given object implements the DocumentTypeAdd interface.
 */
export function instanceOfDocumentTypeAdd(value: object): value is DocumentTypeAdd {
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    return true;
}

export function DocumentTypeAddFromJSON(json: any): DocumentTypeAdd {
    return DocumentTypeAddFromJSONTyped(json, false);
}

export function DocumentTypeAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTypeAdd {
    if (json == null) {
        return json;
    }
    return {
        
        'documentType': json['document_type'],
    };
}

export function DocumentTypeAddToJSON(json: any): DocumentTypeAdd {
    return DocumentTypeAddToJSONTyped(json, false);
}

export function DocumentTypeAddToJSONTyped(value?: DocumentTypeAdd | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document_type': value['documentType'],
    };
}

