"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDocumentTypeAdd = instanceOfDocumentTypeAdd;
exports.DocumentTypeAddFromJSON = DocumentTypeAddFromJSON;
exports.DocumentTypeAddFromJSONTyped = DocumentTypeAddFromJSONTyped;
exports.DocumentTypeAddToJSON = DocumentTypeAddToJSON;
exports.DocumentTypeAddToJSONTyped = DocumentTypeAddToJSONTyped;
/**
 * Check if a given object implements the DocumentTypeAdd interface.
 */
function instanceOfDocumentTypeAdd(value) {
    if (!('documentType' in value) || value['documentType'] === undefined)
        return false;
    return true;
}
function DocumentTypeAddFromJSON(json) {
    return DocumentTypeAddFromJSONTyped(json, false);
}
function DocumentTypeAddFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'documentType': json['document_type'],
    };
}
function DocumentTypeAddToJSON(json) {
    return DocumentTypeAddToJSONTyped(json, false);
}
function DocumentTypeAddToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'document_type': value['documentType'],
    };
}
