/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentTypeDriverConfiguration } from './DocumentTypeDriverConfiguration';
import {
    DocumentTypeDriverConfigurationFromJSON,
    DocumentTypeDriverConfigurationFromJSONTyped,
    DocumentTypeDriverConfigurationToJSON,
    DocumentTypeDriverConfigurationToJSONTyped,
} from './DocumentTypeDriverConfiguration';

/**
 * 
 * @export
 * @interface DocumentTypesFileMetadataDriversList200Response
 */
export interface DocumentTypesFileMetadataDriversList200Response {
    /**
     * 
     * @type {number}
     * @memberof DocumentTypesFileMetadataDriversList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentTypesFileMetadataDriversList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentTypesFileMetadataDriversList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<DocumentTypeDriverConfiguration>}
     * @memberof DocumentTypesFileMetadataDriversList200Response
     */
    results: Array<DocumentTypeDriverConfiguration>;
}

/**
 * Check if a given object implements the DocumentTypesFileMetadataDriversList200Response interface.
 */
export function instanceOfDocumentTypesFileMetadataDriversList200Response(value: object): value is DocumentTypesFileMetadataDriversList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function DocumentTypesFileMetadataDriversList200ResponseFromJSON(json: any): DocumentTypesFileMetadataDriversList200Response {
    return DocumentTypesFileMetadataDriversList200ResponseFromJSONTyped(json, false);
}

export function DocumentTypesFileMetadataDriversList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTypesFileMetadataDriversList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(DocumentTypeDriverConfigurationFromJSON)),
    };
}

export function DocumentTypesFileMetadataDriversList200ResponseToJSON(json: any): DocumentTypesFileMetadataDriversList200Response {
    return DocumentTypesFileMetadataDriversList200ResponseToJSONTyped(json, false);
}

export function DocumentTypesFileMetadataDriversList200ResponseToJSONTyped(value?: DocumentTypesFileMetadataDriversList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(DocumentTypeDriverConfigurationToJSON)),
    };
}

