"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentVersionModificationExecuteBackendIdEnum = void 0;
exports.instanceOfDocumentVersionModificationExecute = instanceOfDocumentVersionModificationExecute;
exports.DocumentVersionModificationExecuteFromJSON = DocumentVersionModificationExecuteFromJSON;
exports.DocumentVersionModificationExecuteFromJSONTyped = DocumentVersionModificationExecuteFromJSONTyped;
exports.DocumentVersionModificationExecuteToJSON = DocumentVersionModificationExecuteToJSON;
exports.DocumentVersionModificationExecuteToJSONTyped = DocumentVersionModificationExecuteToJSONTyped;
/**
 * @export
 */
exports.DocumentVersionModificationExecuteBackendIdEnum = {
    MayanAppsDocumentsDocumentVersionModificationsDocumentVersionModificationPagesAppend: 'mayan.apps.documents.document_version_modifications.DocumentVersionModificationPagesAppend',
    MayanAppsDocumentsDocumentVersionModificationsDocumentVersionModificationPagesReset: 'mayan.apps.documents.document_version_modifications.DocumentVersionModificationPagesReset'
};
/**
 * Check if a given object implements the DocumentVersionModificationExecute interface.
 */
function instanceOfDocumentVersionModificationExecute(value) {
    if (!('backendId' in value) || value['backendId'] === undefined)
        return false;
    return true;
}
function DocumentVersionModificationExecuteFromJSON(json) {
    return DocumentVersionModificationExecuteFromJSONTyped(json, false);
}
function DocumentVersionModificationExecuteFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'backendId': json['backend_id'],
    };
}
function DocumentVersionModificationExecuteToJSON(json) {
    return DocumentVersionModificationExecuteToJSONTyped(json, false);
}
function DocumentVersionModificationExecuteToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'backend_id': value['backendId'],
    };
}
