/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentChangeType
 */
export interface DocumentChangeType {
    /**
     * Primary key of the document type into which the document will be changed.
     * @type {string}
     * @memberof DocumentChangeType
     */
    'document_type_id': string;
}

