"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDocumentsFilesSourceMetadataList200Response = instanceOfDocumentsFilesSourceMetadataList200Response;
exports.DocumentsFilesSourceMetadataList200ResponseFromJSON = DocumentsFilesSourceMetadataList200ResponseFromJSON;
exports.DocumentsFilesSourceMetadataList200ResponseFromJSONTyped = DocumentsFilesSourceMetadataList200ResponseFromJSONTyped;
exports.DocumentsFilesSourceMetadataList200ResponseToJSON = DocumentsFilesSourceMetadataList200ResponseToJSON;
exports.DocumentsFilesSourceMetadataList200ResponseToJSONTyped = DocumentsFilesSourceMetadataList200ResponseToJSONTyped;
const DocumentFileSourceMetadata_1 = require("./DocumentFileSourceMetadata");
/**
 * Check if a given object implements the DocumentsFilesSourceMetadataList200Response interface.
 */
function instanceOfDocumentsFilesSourceMetadataList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function DocumentsFilesSourceMetadataList200ResponseFromJSON(json) {
    return DocumentsFilesSourceMetadataList200ResponseFromJSONTyped(json, false);
}
function DocumentsFilesSourceMetadataList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(DocumentFileSourceMetadata_1.DocumentFileSourceMetadataFromJSON)),
    };
}
function DocumentsFilesSourceMetadataList200ResponseToJSON(json) {
    return DocumentsFilesSourceMetadataList200ResponseToJSONTyped(json, false);
}
function DocumentsFilesSourceMetadataList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(DocumentFileSourceMetadata_1.DocumentFileSourceMetadataToJSON)),
    };
}
