/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DownloadFile } from './download-file';

/**
 * 
 * @export
 * @interface DownloadsList200Response
 */
export interface DownloadsList200Response {
    /**
     * 
     * @type {number}
     * @memberof DownloadsList200Response
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof DownloadsList200Response
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DownloadsList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<DownloadFile>}
     * @memberof DownloadsList200Response
     */
    'results': Array<DownloadFile>;
}

