"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDownloadsList200Response = instanceOfDownloadsList200Response;
exports.DownloadsList200ResponseFromJSON = DownloadsList200ResponseFromJSON;
exports.DownloadsList200ResponseFromJSONTyped = DownloadsList200ResponseFromJSONTyped;
exports.DownloadsList200ResponseToJSON = DownloadsList200ResponseToJSON;
exports.DownloadsList200ResponseToJSONTyped = DownloadsList200ResponseToJSONTyped;
const DownloadFile_1 = require("./DownloadFile");
/**
 * Check if a given object implements the DownloadsList200Response interface.
 */
function instanceOfDownloadsList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function DownloadsList200ResponseFromJSON(json) {
    return DownloadsList200ResponseFromJSONTyped(json, false);
}
function DownloadsList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(DownloadFile_1.DownloadFileFromJSON)),
    };
}
function DownloadsList200ResponseToJSON(json) {
    return DownloadsList200ResponseToJSONTyped(json, false);
}
function DownloadsList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(DownloadFile_1.DownloadFileToJSON)),
    };
}
