/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventTypeNamespace
 */
export interface EventTypeNamespace {
    /**
     * 
     * @type {string}
     * @memberof EventTypeNamespace
     */
    'event_types_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventTypeNamespace
     */
    'label': string;
    /**
     * 
     * @type {string}
     * @memberof EventTypeNamespace
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof EventTypeNamespace
     */
    'url'?: string;
}

