"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfEventType = instanceOfEventType;
exports.EventTypeFromJSON = EventTypeFromJSON;
exports.EventTypeFromJSONTyped = EventTypeFromJSONTyped;
exports.EventTypeToJSON = EventTypeToJSON;
exports.EventTypeToJSONTyped = EventTypeToJSONTyped;
/**
 * Check if a given object implements the EventType interface.
 */
function instanceOfEventType(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('label' in value) || value['label'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    return true;
}
function EventTypeFromJSON(json) {
    return EventTypeFromJSONTyped(json, false);
}
function EventTypeFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'eventTypeNamespaceUrl': json['event_type_namespace_url'] == null ? undefined : json['event_type_namespace_url'],
        'id': json['id'],
        'label': json['label'],
        'name': json['name'],
    };
}
function EventTypeToJSON(json) {
    return EventTypeToJSONTyped(json, false);
}
function EventTypeToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'label': value['label'],
        'name': value['name'],
    };
}
