"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfIndexInstance = instanceOfIndexInstance;
exports.IndexInstanceFromJSON = IndexInstanceFromJSON;
exports.IndexInstanceFromJSONTyped = IndexInstanceFromJSONTyped;
exports.IndexInstanceToJSON = IndexInstanceToJSON;
exports.IndexInstanceToJSONTyped = IndexInstanceToJSONTyped;
/**
 * Check if a given object implements the IndexInstance interface.
 */
function instanceOfIndexInstance(value) {
    return true;
}
function IndexInstanceFromJSON(json) {
    return IndexInstanceFromJSONTyped(json, false);
}
function IndexInstanceFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'depth': json['depth'] == null ? undefined : json['depth'],
        'label': json['label'] == null ? undefined : json['label'],
        'id': json['id'] == null ? undefined : json['id'],
        'nodesUrl': json['nodes_url'] == null ? undefined : json['nodes_url'],
        'nodeCount': json['node_count'] == null ? undefined : json['node_count'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}
function IndexInstanceToJSON(json) {
    return IndexInstanceToJSONTyped(json, false);
}
function IndexInstanceToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {};
}
