"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfIndexTemplatesNodesList200Response = instanceOfIndexTemplatesNodesList200Response;
exports.IndexTemplatesNodesList200ResponseFromJSON = IndexTemplatesNodesList200ResponseFromJSON;
exports.IndexTemplatesNodesList200ResponseFromJSONTyped = IndexTemplatesNodesList200ResponseFromJSONTyped;
exports.IndexTemplatesNodesList200ResponseToJSON = IndexTemplatesNodesList200ResponseToJSON;
exports.IndexTemplatesNodesList200ResponseToJSONTyped = IndexTemplatesNodesList200ResponseToJSONTyped;
const IndexTemplateNode_1 = require("./IndexTemplateNode");
/**
 * Check if a given object implements the IndexTemplatesNodesList200Response interface.
 */
function instanceOfIndexTemplatesNodesList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function IndexTemplatesNodesList200ResponseFromJSON(json) {
    return IndexTemplatesNodesList200ResponseFromJSONTyped(json, false);
}
function IndexTemplatesNodesList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(IndexTemplateNode_1.IndexTemplateNodeFromJSON)),
    };
}
function IndexTemplatesNodesList200ResponseToJSON(json) {
    return IndexTemplatesNodesList200ResponseToJSONTyped(json, false);
}
function IndexTemplatesNodesList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(IndexTemplateNode_1.IndexTemplateNodeToJSON)),
    };
}
