/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MailingProfile } from './mailing-profile';

/**
 * 
 * @export
 * @interface MailingProfilesList200Response
 */
export interface MailingProfilesList200Response {
    /**
     * 
     * @type {number}
     * @memberof MailingProfilesList200Response
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof MailingProfilesList200Response
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MailingProfilesList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<MailingProfile>}
     * @memberof MailingProfilesList200Response
     */
    'results': Array<MailingProfile>;
}

