/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MetadataType
 */
export interface MetadataType {
    /**
     * Enter a template to render.
     * @type {string}
     * @memberof MetadataType
     */
    'default'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MetadataType
     */
    'id'?: number;
    /**
     * Short description of this metadata type.
     * @type {string}
     * @memberof MetadataType
     */
    'label': string;
    /**
     * Enter a template to render. Must result in a comma delimited string.
     * @type {string}
     * @memberof MetadataType
     */
    'lookup'?: string | null;
    /**
     * Name used by other apps to reference this metadata type. Do not use python reserved words, or spaces.
     * @type {string}
     * @memberof MetadataType
     */
    'name': string;
    /**
     * The parser will reformat the value entered to conform to the expected format.
     * @type {string}
     * @memberof MetadataType
     */
    'parser'?: string;
    /**
     * Enter the arguments for the parser in YAML format.
     * @type {string}
     * @memberof MetadataType
     */
    'parser_arguments'?: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataType
     */
    'url'?: string;
    /**
     * The validator will reject data entry if the value entered does not conform to the expected format.
     * @type {string}
     * @memberof MetadataType
     */
    'validation'?: string;
    /**
     * Enter the arguments for the validator in YAML format.
     * @type {string}
     * @memberof MetadataType
     */
    'validation_arguments'?: string;
}

