/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Document } from './document';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface RecentlyAccessedDocument
 */
export interface RecentlyAccessedDocument {
    /**
     * 
     * @type {Document}
     * @memberof RecentlyAccessedDocument
     */
    'document'?: Document;
    /**
     * 
     * @type {number}
     * @memberof RecentlyAccessedDocument
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecentlyAccessedDocument
     */
    'datetime_accessed'?: string;
    /**
     * 
     * @type {User}
     * @memberof RecentlyAccessedDocument
     */
    'user'?: User;
}

