"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRolePermissionAdd = instanceOfRolePermissionAdd;
exports.RolePermissionAddFromJSON = RolePermissionAddFromJSON;
exports.RolePermissionAddFromJSONTyped = RolePermissionAddFromJSONTyped;
exports.RolePermissionAddToJSON = RolePermissionAddToJSON;
exports.RolePermissionAddToJSONTyped = RolePermissionAddToJSONTyped;
/**
 * Check if a given object implements the RolePermissionAdd interface.
 */
function instanceOfRolePermissionAdd(value) {
    if (!('permission' in value) || value['permission'] === undefined)
        return false;
    return true;
}
function RolePermissionAddFromJSON(json) {
    return RolePermissionAddFromJSONTyped(json, false);
}
function RolePermissionAddFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'permission': json['permission'],
    };
}
function RolePermissionAddToJSON(json) {
    return RolePermissionAddToJSONTyped(json, false);
}
function RolePermissionAddToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'permission': value['permission'],
    };
}
