"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRoleGroupRemove = instanceOfRoleGroupRemove;
exports.RoleGroupRemoveFromJSON = RoleGroupRemoveFromJSON;
exports.RoleGroupRemoveFromJSONTyped = RoleGroupRemoveFromJSONTyped;
exports.RoleGroupRemoveToJSON = RoleGroupRemoveToJSON;
exports.RoleGroupRemoveToJSONTyped = RoleGroupRemoveToJSONTyped;
/**
 * Check if a given object implements the RoleGroupRemove interface.
 */
function instanceOfRoleGroupRemove(value) {
    if (!('group' in value) || value['group'] === undefined)
        return false;
    return true;
}
function RoleGroupRemoveFromJSON(json) {
    return RoleGroupRemoveFromJSONTyped(json, false);
}
function RoleGroupRemoveFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'group': json['group'],
    };
}
function RoleGroupRemoveToJSON(json) {
    return RoleGroupRemoveToJSONTyped(json, false);
}
function RoleGroupRemoveToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'group': value['group'],
    };
}
