/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleGroupAdd
 */
export interface RoleGroupAdd {
    /**
     * Primary key of the group to add to the role.
     * @type {string}
     * @memberof RoleGroupAdd
     */
    'group': string;
}

