/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SavedResultset } from './SavedResultset';
import {
    SavedResultsetFromJSON,
    SavedResultsetFromJSONTyped,
    SavedResultsetToJSON,
    SavedResultsetToJSONTyped,
} from './SavedResultset';

/**
 * 
 * @export
 * @interface SavedResultsetsList200Response
 */
export interface SavedResultsetsList200Response {
    /**
     * 
     * @type {number}
     * @memberof SavedResultsetsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof SavedResultsetsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SavedResultsetsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SavedResultset>}
     * @memberof SavedResultsetsList200Response
     */
    results: Array<SavedResultset>;
}

/**
 * Check if a given object implements the SavedResultsetsList200Response interface.
 */
export function instanceOfSavedResultsetsList200Response(value: object): value is SavedResultsetsList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function SavedResultsetsList200ResponseFromJSON(json: any): SavedResultsetsList200Response {
    return SavedResultsetsList200ResponseFromJSONTyped(json, false);
}

export function SavedResultsetsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SavedResultsetsList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SavedResultsetFromJSON)),
    };
}

export function SavedResultsetsList200ResponseToJSON(json: any): SavedResultsetsList200Response {
    return SavedResultsetsList200ResponseToJSONTyped(json, false);
}

export function SavedResultsetsList200ResponseToJSONTyped(value?: SavedResultsetsList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SavedResultsetToJSON)),
    };
}

