/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmartLink
 */
export interface SmartLink {
    /**
     * 
     * @type {string}
     * @memberof SmartLink
     */
    readonly conditionsUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartLink
     */
    readonly documentTypesUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartLink
     */
    readonly documentTypesAddUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SmartLink
     */
    readonly documentTypesRemoveUrl?: string;
    /**
     * Use this field to show a unique label depending on the document from which the smart link is being accessed.
     * @type {string}
     * @memberof SmartLink
     */
    dynamicLabel?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SmartLink
     */
    enabled?: boolean;
    /**
     * A short text describing the smart link.
     * @type {string}
     * @memberof SmartLink
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof SmartLink
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof SmartLink
     */
    readonly url?: string;
}

/**
 * Check if a given object implements the SmartLink interface.
 */
export function instanceOfSmartLink(value: object): value is SmartLink {
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function SmartLinkFromJSON(json: any): SmartLink {
    return SmartLinkFromJSONTyped(json, false);
}

export function SmartLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmartLink {
    if (json == null) {
        return json;
    }
    return {
        
        'conditionsUrl': json['conditions_url'] == null ? undefined : json['conditions_url'],
        'documentTypesUrl': json['document_types_url'] == null ? undefined : json['document_types_url'],
        'documentTypesAddUrl': json['document_types_add_url'] == null ? undefined : json['document_types_add_url'],
        'documentTypesRemoveUrl': json['document_types_remove_url'] == null ? undefined : json['document_types_remove_url'],
        'dynamicLabel': json['dynamic_label'] == null ? undefined : json['dynamic_label'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'label': json['label'],
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function SmartLinkToJSON(json: any): SmartLink {
    return SmartLinkToJSONTyped(json, false);
}

export function SmartLinkToJSONTyped(value?: Omit<SmartLink, 'conditions_url'|'document_types_url'|'document_types_add_url'|'document_types_remove_url'|'id'|'url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dynamic_label': value['dynamicLabel'],
        'enabled': value['enabled'],
        'label': value['label'],
    };
}

