/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    'actions_url'?: string;
    /**
     * JSON encoded data for the backend class.
     * @type {string}
     * @memberof Source
     */
    'backend_data'?: string;
    /**
     * The dotted Python path to the backend class.
     * @type {string}
     * @memberof Source
     */
    'backend_path': string;
    /**
     * 
     * @type {boolean}
     * @memberof Source
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Source
     */
    'id'?: number;
    /**
     * A short text to describe this source.
     * @type {string}
     * @memberof Source
     */
    'label': string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    'url'?: string;
}

