"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSourcesActionsList200Response = instanceOfSourcesActionsList200Response;
exports.SourcesActionsList200ResponseFromJSON = SourcesActionsList200ResponseFromJSON;
exports.SourcesActionsList200ResponseFromJSONTyped = SourcesActionsList200ResponseFromJSONTyped;
exports.SourcesActionsList200ResponseToJSON = SourcesActionsList200ResponseToJSON;
exports.SourcesActionsList200ResponseToJSONTyped = SourcesActionsList200ResponseToJSONTyped;
const SourceBackendAction_1 = require("./SourceBackendAction");
/**
 * Check if a given object implements the SourcesActionsList200Response interface.
 */
function instanceOfSourcesActionsList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function SourcesActionsList200ResponseFromJSON(json) {
    return SourcesActionsList200ResponseFromJSONTyped(json, false);
}
function SourcesActionsList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(SourceBackendAction_1.SourceBackendActionFromJSON)),
    };
}
function SourcesActionsList200ResponseToJSON(json) {
    return SourcesActionsList200ResponseToJSONTyped(json, false);
}
function SourcesActionsList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(SourceBackendAction_1.SourceBackendActionToJSON)),
    };
}
