"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTemplatesList200Response = instanceOfTemplatesList200Response;
exports.TemplatesList200ResponseFromJSON = TemplatesList200ResponseFromJSON;
exports.TemplatesList200ResponseFromJSONTyped = TemplatesList200ResponseFromJSONTyped;
exports.TemplatesList200ResponseToJSON = TemplatesList200ResponseToJSON;
exports.TemplatesList200ResponseToJSONTyped = TemplatesList200ResponseToJSONTyped;
const AJAXTemplate_1 = require("./AJAXTemplate");
/**
 * Check if a given object implements the TemplatesList200Response interface.
 */
function instanceOfTemplatesList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function TemplatesList200ResponseFromJSON(json) {
    return TemplatesList200ResponseFromJSONTyped(json, false);
}
function TemplatesList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(AJAXTemplate_1.AJAXTemplateFromJSON)),
    };
}
function TemplatesList200ResponseToJSON(json) {
    return TemplatesList200ResponseToJSONTyped(json, false);
}
function TemplatesList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(AJAXTemplate_1.AJAXTemplateToJSON)),
    };
}
