"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTrashedDocumentsList200Response = instanceOfTrashedDocumentsList200Response;
exports.TrashedDocumentsList200ResponseFromJSON = TrashedDocumentsList200ResponseFromJSON;
exports.TrashedDocumentsList200ResponseFromJSONTyped = TrashedDocumentsList200ResponseFromJSONTyped;
exports.TrashedDocumentsList200ResponseToJSON = TrashedDocumentsList200ResponseToJSON;
exports.TrashedDocumentsList200ResponseToJSONTyped = TrashedDocumentsList200ResponseToJSONTyped;
const TrashedDocument_1 = require("./TrashedDocument");
/**
 * Check if a given object implements the TrashedDocumentsList200Response interface.
 */
function instanceOfTrashedDocumentsList200Response(value) {
    if (!('count' in value) || value['count'] === undefined)
        return false;
    if (!('results' in value) || value['results'] === undefined)
        return false;
    return true;
}
function TrashedDocumentsList200ResponseFromJSON(json) {
    return TrashedDocumentsList200ResponseFromJSONTyped(json, false);
}
function TrashedDocumentsList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': (json['results'].map(TrashedDocument_1.TrashedDocumentFromJSON)),
    };
}
function TrashedDocumentsList200ResponseToJSON(json) {
    return TrashedDocumentsList200ResponseToJSONTyped(json, false);
}
function TrashedDocumentsList200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': (value['results'].map(TrashedDocument_1.TrashedDocumentToJSON)),
    };
}
