/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowTemplateDocumentTypeRemove
 */
export interface WorkflowTemplateDocumentTypeRemove {
    /**
     * Primary key of the document type to remove from the workflow.
     * @type {string}
     * @memberof WorkflowTemplateDocumentTypeRemove
     */
    documentTypeId: string;
}

/**
 * Check if a given object implements the WorkflowTemplateDocumentTypeRemove interface.
 */
export function instanceOfWorkflowTemplateDocumentTypeRemove(value: object): value is WorkflowTemplateDocumentTypeRemove {
    if (!('documentTypeId' in value) || value['documentTypeId'] === undefined) return false;
    return true;
}

export function WorkflowTemplateDocumentTypeRemoveFromJSON(json: any): WorkflowTemplateDocumentTypeRemove {
    return WorkflowTemplateDocumentTypeRemoveFromJSONTyped(json, false);
}

export function WorkflowTemplateDocumentTypeRemoveFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTemplateDocumentTypeRemove {
    if (json == null) {
        return json;
    }
    return {
        
        'documentTypeId': json['document_type_id'],
    };
}

export function WorkflowTemplateDocumentTypeRemoveToJSON(json: any): WorkflowTemplateDocumentTypeRemove {
    return WorkflowTemplateDocumentTypeRemoveToJSONTyped(json, false);
}

export function WorkflowTemplateDocumentTypeRemoveToJSONTyped(value?: WorkflowTemplateDocumentTypeRemove | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document_type_id': value['documentTypeId'],
    };
}

