/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowInstanceLaunch
 */
export interface WorkflowInstanceLaunch {
    /**
     * Primary key of the workflow template to launch.
     * @type {string}
     * @memberof WorkflowInstanceLaunch
     */
    'workflow_template_id': string;
}

