/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowTemplate } from './WorkflowTemplate';
import {
    WorkflowTemplateFromJSON,
    WorkflowTemplateFromJSONTyped,
    WorkflowTemplateToJSON,
    WorkflowTemplateToJSONTyped,
} from './WorkflowTemplate';

/**
 * 
 * @export
 * @interface WorkflowTemplatesList200Response
 */
export interface WorkflowTemplatesList200Response {
    /**
     * 
     * @type {number}
     * @memberof WorkflowTemplatesList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTemplatesList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTemplatesList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<WorkflowTemplate>}
     * @memberof WorkflowTemplatesList200Response
     */
    results: Array<WorkflowTemplate>;
}

/**
 * Check if a given object implements the WorkflowTemplatesList200Response interface.
 */
export function instanceOfWorkflowTemplatesList200Response(value: object): value is WorkflowTemplatesList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function WorkflowTemplatesList200ResponseFromJSON(json: any): WorkflowTemplatesList200Response {
    return WorkflowTemplatesList200ResponseFromJSONTyped(json, false);
}

export function WorkflowTemplatesList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTemplatesList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(WorkflowTemplateFromJSON)),
    };
}

export function WorkflowTemplatesList200ResponseToJSON(json: any): WorkflowTemplatesList200Response {
    return WorkflowTemplatesList200ResponseToJSONTyped(json, false);
}

export function WorkflowTemplatesList200ResponseToJSONTyped(value?: WorkflowTemplatesList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(WorkflowTemplateToJSON)),
    };
}

