/* tslint:disable */
/* eslint-disable */
/**
 * Mayan EDMS API
 * Free Open Source Electronic Document Management System
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DocumentVersionModificationBackendsList200Response,
} from '../models/index';
import {
    DocumentVersionModificationBackendsList200ResponseFromJSON,
    DocumentVersionModificationBackendsList200ResponseToJSON,
} from '../models/index';

export interface DocumentVersionModificationBackendsListRequest {
    ordering?: string;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class DocumentVersionModificationBackendsApi extends runtime.BaseAPI {

    /**
     * Returns a list of the available document version modification backends.
     */
    async documentVersionModificationBackendsListRaw(requestParameters: DocumentVersionModificationBackendsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentVersionModificationBackendsList200Response>> {
        const queryParameters: any = {};

        if (requestParameters['ordering'] != null) {
            queryParameters['_ordering'] = requestParameters['ordering'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/document_version_modification_backends/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentVersionModificationBackendsList200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of the available document version modification backends.
     */
    async documentVersionModificationBackendsList(requestParameters: DocumentVersionModificationBackendsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentVersionModificationBackendsList200Response> {
        const response = await this.documentVersionModificationBackendsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
